function sampleMusic()
    -- An ABC tune is a string with newline characters to denote new lines.
    -- See the many web pages on ABC musical notation to get a tune or an understanding of
    -- this allegedly human- and machine-readable format.  
    -- You could even write your own by hand or use another program to convert a MIDI file.

winTune = 'X:1\n'
..'T:Celestial Boogie\n'
..'I:abc-version 2.1\n'
..'I:abc-creator MidiZyx2abc 1.01\n'
..'I:linebreak $\n'
..'I:continueall true\n'
..'M:C\n'
..'L:1/8\n'
..'Q:1/4=120\n'
..'K:C\n'
..'!pp!\n'
..'[F^gc\'][Fa][^G_bd\'][Agc\'][ca][c_bd\'][dgc\'][ca]| % 1\n'
..'[F_bd\'][F^gc\'][^Ga][A_bd\'][cgc\'][ca][d_bd\'][cgc\']| % 2\n'
..'[Fa][F_bd\'][^G^gc\'][Aa][c_bd\'][c^gc\'][da][c_bd\']| % 3\n'
..'[F^gc\'][Fa][^G_bd\'][Agc\'][ca][c_bd\'][dgc\'][ca]| % 4\n'
..'[_B_bd\'][_B^g][^ca][d_bd\'][f^g][fa][=g_bd\'][f^g]| % 5\n'
..'[_Ba][_B_bd\'][^c^g][da][f_bd\'][f^g][=ga][f_bd\']| % 6\n'
..'[F^gc\'][Fa][^G_bd\'][A^gc\'][=ca][c_bd\'][d^gc\'][ca]| % 7\n'
..'[F^g][Fa][^G_bd\'][A^gc\'][ca][c_bd\'][d^gc\'][ca]| % 8\n'
..'[c^d\'^f\'][ce\'g\'][^dc\'][e=f\'a\']=g[gc\'][ad\'^f\'][gc\'e\'g\']| % 9\n'
..'[_B1/2=d\'1/2][d\'1/2=f\'1/2][_Bc\'][^cc\'-_e\'][c\'=d][f_bd\'][fac\'][g_b][fg]| % 10\n'
..'[Fac\'][Ff][^G_bd\'][Af_bd\'][=c1/2^g1/2c\'1/2]a1/2[cf][d_bd\'][cf_bd\']| % 11\n'
..'[c1/2^g1/2c\'1/2]a1/2[cf][c-^d][c-e][c=g]gag|] % 12 \n'

winTune ='X:1\n'
..'T:win boogie\n'
..'M:C\n'
..'L:1/8\n'
..'Q:1/4=120\n'
..'K:C\n'
..'!pp!\n'
..'[Dff\'][da][Fd\'][Gf-f\'-][f\'f^G][Aa][A,d\'][Af-f\'-]| % 1\n'
..'[f\'fD][da][Fd\'][=Gf-f\'-][f\'f^G][Aa][d\'A,]\n'
..'[Aff\']| % 2\n'
..'[A,ee\'][Aa][Cc\'][De-e\'-][e\'e^D][Ea][E,c\']E| % 3\n'
..'[Cee\'][cg][Ec\'][Fe-e\'-][e\'e^F][Gg][G,c\']G| % 4\n'
..'[Dff\'][da][=Fd\'][Gf-f\'-][f\'f^G][Aa][A,d\']A| % 5\n'
..'[Dff\'][da][Fd\'][=Gf-f\'-][f\'f^G][Aa][A,d\'][Af-f\'-]| % 6\n'
..'[f\'fD][da][Fd\'][=Gf-f\'-][f\'f^G][Aa][d\'A,]\n'
..'[Aff\']| % 7\n'
..'[A,ee\'][Aa][Cc\'][De-e\'-][e\'e^D][Ea][E,c\']E| % 8\n'
..'[Cee\'][cg][Ec\'][Fe-e\'-][e\'e^F][Gg][G,c\']G| % 9\n'
..'[Dff\'][da][=Fd\'][Gf-f\'-][f\'f^G][Aa][A,d\']A| % 10\n'
..'D1/4-[D1/4-a1/4][D1/4-d\'1/4][D1/4f\'1/4][da\'][Fd\'\'][=G1/2-f\'\'1/2]\n'
..'[G1/4-d\'\'1/4][G1/4f\'\'1/4]\n'
..'[^Gd\'\'][Aa\'][A,d\'\'][Aa\']| % 11\n'
..'D[d1/4-a1/4][d1/4-d\'1/4][d1/2f\'1/2][a\'-F]\n'
..'[a\'1/4=G1/4-][G3/4d\'\'3/4-][d\'\'1/4^G1/4-]\n'
..'[G3/4f\'\'3/4-][f\'\'1/4A1/4-][A3/4d\'\'3/4-]\n'
..'[d\'\'1/4A,1/4-][A,3/4a\'3/4-f\'\'3/4-][f\'\'a\'A]| \n'
..'% 12\n'
..'A,A1/4-[A1/4-a1/4][A1/4-c\'1/4][A1/4e\'1/4-][e\'1/4C1/4-]\n'
..'[C3/4a\'3/4][De\'][^Dc\'][Ea][E,c\'][Eae\']| \n'
..'% 13\n'
..'[C1/4-c\'1/4][C1/2-g\'1/2][C1/4e\'1/4-][e\'1/4c1/4-]\n'
..'[c1/2-c\'1/2][c1/4e\'1/4-][e\'E][Fc\'][^Fg]\n'
..'[Gc\'][G,g-][gG]| % 14\n'
..'[Dff\'][da][=Fd\'][Gf-f\'-][f\'f^G][Aa][A,d\']A| % 10\n'

startTune = 'X:1\n'
..'T:midi_export\n'
..'I:abc-version 2.1\n'
..'I:abc-creator MidiZyx2abc 1.01\n'
..'I:linebreak $\n'
..'I:continueall true\n'
..'M:12/8\n'
..'L:1/8\n'
..'Q:12/8=240\n'
..'K:C\n'
..'!pp!|:"Dm"[D24f\']d\'afdA !pp!f\'d\'afdA !pp! f\'d\'afdA !pp! f\'d\'afdA|\n'
..'!pp! [D24f\']d\'afdA f\'d\'afdA f\'d\'afdA f\'d\'afdA|\n'
..'!p!"Am"[A24e\']c\'aecA e\'c\'aecA e\'c\'aecA e\'c\'aecA|\n'
..'!p!"C"[C24e\']c\'gecG e\'c\'gecG e\'c\'gecG e\'c\'gecG:|'
..'!p!"Dm"[D,24Df\']d\'afdA !pp!f\'d\'afdA !pp!f\'d\'afdA !pp!f\'d\'afdA|\n'

tutorialTune = 'X:1\n'
..'T:Craw_new2\n'
..'I:abc-version 2.1\n'
..'I:abc-creator MidiZyx2abc 1.01\n'
..'I:linebreak $\n'
..'I:continueall true\n'
..'M:C\n'
..'L:1/8\n'
..'Q:1/4=110\n'
..'K:F\n'
..'%%MIDI program 0 % Grand Piano\n'
..'!pp!\n'
..'A,DFDA,DFD| A,DFDA,DFD| [A,a-][aD][Ff-][fD][A,g-][gD][Fe-][eD]| % 3\n'
..'[A,f-][fD][Fd-][dD][A,e-][eD][Fc-][cD]| % 4\n'
..'[_B,d-][d-D][d-F][d-D][d-B,][d-D][d-F][dD]| _B,DFDB,DFD| % 6\n'
..'[A,a-][aD][Ff-][fD][A,g-][gD][Fe-][eD]| % 7\n'
..'[A,f-][fD][Fd-][dD][A,e-][eD][Fc-][cD]| % 8\n'
..'[A,A-][A-^C][A-E][A-^C][A-A,][A-^C][A-E][A^C]| A,^CECA,^CE^C| % 10\n'
..'A,DFDA,DFD| A,DFDA,DFD| [A,f][Da-][aF][Df][A,a-][aD][Ff][Da-]| % 13\n'
..'[aA,][Df][Fa-][aD][A,f][Da-][aF][Df]| % 14\n'
..'[A,a-][aD][Ff][Da-][aA,][Df][Fa-][aD]| % 15\n'
..'[A,f][Da-][aF][Df][A,a-][aD][Ff-][fD]| % 16\n'
..'[_B,_B-d-g-][g-d-B-D][BdgF][DB-d-g-][g-d-B-B,][B-d-g-D][g-d-B-F][BdgD]| % 17\n'
..'_B,[Dd-][dF][Dg-][gB,][Dd][Fg-][gD]| % 18\n'
..'[A,f-][f-D][fF][Dd-][d-A,][d-D][d-F][d-D]| % 19\n'
..'[d-A,][dD][Fd][Da-][aA,][Dd][Fa-][aD]| % 20\n'
..'[A,A-^c-e-][e-^c-A-^C][A^ceE][^Ce-][e-A,][e-^C][e-E][e-^C]| % 21\n'
..'[eA,][^C^c-][^cE][^Ce-][eA,][^C^c][Ee-][e^C]| % 22\n'
..'[A,DA-d-][d-A-D][AdF][DA-d-][d-A-A,][A-d-D][d-A-F][A-d-D]| % 23\n'
..'[d-A-A,][A-d-D][d-A-F][A-d-D][d-A-A,][A-d-D][d-A-F][AdD]| % 24\n'
..'[A,f\'][Dd\'-][d\'F][Dd\'-][d\'A,][Dd\'-][d\'F][Dd\']| % 25\n'
..'[A,f\'][Dd\'-][d\'F][Dd\'-][d\'A,][Dd\'-][d\'F][Dd\']| % 26\n'
..'[A,f\'][Dd\'-][d\'F][Dd\'-][d\'A,][Dd\'-][d\'F][Dd\']| % 27\n'
..'[A,f\'][Dd\'-][d\'F][Dd\'-][d\'A,][Dd\'-][d\'F][Dd\']| % 28\n'
..'[_B,f\'][Dd\'-][d\'F][Dd\'-][d\'B,][Dd\'-][d\'F][Dd\']| % 29\n'
..'[_B,f\'][Dd\'-][d\'F][Dd\'-][d\'B,][Dd\'-][d\'F][Dd\']| % 30\n'
..'[A,f\'][Dd\'-][d\'F][Dd\'-][d\'A,][Dd\'-][d\'F][Dd\']| % 31\n'
..'[A,f\'][Dd\'-][d\'F][Dd\'-][d\'A,][Dd\'-][d\'F][Dd\']| % 32\n'
..'[A,c\'][^Ca-][aE][^Ca-][aA,][^Ca-][aE][^Ca]| % 33\n'
..'[A,c\'][^Ca-][aE][^Ca-][aA,][^Ca-][aE][^Cg]| % 34\n'
..'[A,f-][f-D][fF][Df\'-][f\'-A,][f\'-D][f\'-F][f\'D]| % 35\n'
..'[A,d-][d-D][d-F][d-D][d-A,][d-D][dF]D|] % 36 \n'

end
